services:
  db:
    image: postgis/postgis:15-3.3
    container_name: aps_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: aps_health_data
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aps_health_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./data/raw:/app/data/raw
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: