FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Usar caminho absoluto para garantir que encontre o arquivo
CMD ["python", "/app/src/main.py"]