# .streamlit/config.toml

[theme]
# Define a base do tema como claro.
base="light"

# A cor de destaque ROXA para o item selecionado. Esta é a mudança mais importante.
primaryColor="#76BFAC"

# Fundo branco para a área de conteúdo principal.
backgroundColor="#FFFFFF"

# Fundo branco para a sidebar.
secondaryBackgroundColor="#FFFFFF"

# Cor de texto escura padrão.
textColor="#1E202A"

# Fonte.
font="sans serif"