

    MAPBOX_API_KEY = "pk.eyJ1IjoiZXJpY2RpYXNibHUiLCJhIjoiY21mc3Y1MWdpMGEwcTJpcTExOHM1dmxyOSJ9.F2M3UEfjxfjWsIC0j8oLcA"

    [connections.postgresql]
    dialect = "postgresql"
    driver = "psycopg2"
    host = "aps_postgres_db"
    port = 5432
    database = "aps_health_data"
    username = "admin"
    password = "password123"